name: CI/CD Pipeline

on:
  push:
    branches: [ master ] # Or your default branch
  pull_request:
    branches: [ master ] # Or your default branch
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  test-lint-type-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' #saving minutes on gh actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install uv
        uv venv .venv
        source .venv/bin/activate
        uv sync --all-groups
        uv pip install .

    - name: Lint with Ruff
      run: |
        uv run ruff check src tests

    # - name: Type check with Mypy
    #   run: |
    #     mypy src

    - name: Run tests with Pytest
      run: |
        uv run pytest tests

  build-docs:
    runs-on: ubuntu-latest
    needs: test-lint-type-build # Run only if tests pass
    if: github.ref == 'refs/heads/master' # Build docs only on master branch merge

    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
            
        - name: Build-docs
          run: |
            pip install uv
            uv venv .venv
            source .venv/bin/activate
            uv sync --all-groups
            uv pip install .
            cd docs && uv run sphinx-build -b html . _build/html
               
        - name: Setup Pages
          uses: actions/configure-pages@v5
            
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: 'docs/_build/html'  # Removed extra space
              
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4

  bump-version:
    runs-on: ubuntu-latest
    needs: build-docs 
    if: github.ref == 'refs/heads/master' # Build docs only on master branch merge
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
            app-id: ${{ vars.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
        
      - name: Set up Git user
        run: |
            git config --global user.email "ci-bot@example.com"
            git config --global user.name "CI Bot"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version
        run: bump2version patch

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          tags: true

  publish-pypi:
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1


