name: Bump version and publish

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Version part to bump (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
            app-id: ${{ vars.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_KEY }}
    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
            git config --global user.email "ci-bot@example.com"
            git config --global user.name "CI Bot"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version
        run: bump2version ${{ github.event.inputs.part }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          tags: true